--- UNIVERSIDAD MARIANO GALVEZ SEMINARIO DE ANÁLISIS.
--- LILYAN SICA 1990-13-11645. 


-- VER USUARIOS QUE SON ADMINISTRADORES.
SELECT * FROM subasta.vehicles_user WHERE is_superuser = 1;

-- VER USUARIOS REGISTRADOS EN LA APLICACION PARA LA SUBASTA
SELECT * FROM subasta.vehicles_user WHERE is_superuser = 0;
